openapi: 3.2.0
info:
  title: Shyft Customer Deprecated API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Deprecated
paths:
  /api/code_auth/18083836511:
    post:
      tags:
      - Deprecated
      summary: PhoneNumber - Sign in (verify SMS)
      description: 'For the first time, please have `confirm=true` to active this account. otherwise it is not considred as geneated account.


        Once succeeded. Please extract these fields from `Headers` returned:


        `access-token, expiry, token-type, uid, client`


        And please include these headers in your future API calls for authentication purpose.


        `expiry` returns Unix epoch time in seocnds.'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '""'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: sign_in_code
        in: query
        schema:
          type: integer
        example: '9999'
      responses:
        '200':
          description: OK
          headers:
            Platform:
              schema:
                type: string
                example: '{{platform}}'
            Version:
              schema:
                type: string
                example: '{{version}}'
            Build-Number:
              schema:
                type: string
                example: '{{build_number}}'
            Push-Id:
              schema:
                type: string
                example: '{{push_id}}'
            X-Method:
              schema:
                type: string
                example: '{{x_method}}'
            Session-Token:
              schema:
                type: string
                example: '{{session_token}}'
            Session-Uukey:
              schema:
                type: string
                example: '{{session_uukey}}'
            Authorization:
              schema:
                type: string
                example: Token token={{api_key_access_token}}
            Uid:
              schema:
                type: string
                example: '{{uid}}'
            Auth-Category:
              schema:
                type: string
                example: '{{auth_category}}'
            Auth-Target:
              schema:
                type: string
                example: '{{auth_target}}'
            Token-Type:
              schema:
                type: string
                example: Bearer
            Client:
              schema:
                type: string
                example: '{{client}}'
            Access-Token:
              schema:
                type: string
                example: '{{access_token}}'
            Expiry:
              schema:
                type: string
                example: '{{expiry}}'
          content:
            application/json:
              schema:
                type: object
              example: {}
      operationId: postApiCodeAuth18083836511
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
