openapi: 3.2.0
info:
  title: Shyft Customer Compact > Plans API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Compact > Plans
paths:
  /api/compact/plans:
    get:
      tags:
      - Compact > Plans
      summary: get plans
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.19.3
            Date:
              schema:
                type: string
                example: Tue, 25 Jul 2023 12:58:27 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            ETag:
              schema:
                type: string
                example: W/"c405d42c2129464578eb98c8258186ec"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=Rmh3enRlRnR6ZDRFYXR1K21mQ2kzTnNUQ3JFT2QvaXBvQjNORk1HRTY0UGVmejd3cnI2RCtubGdhY1ZVaStRUHBTL1NPQnhLVWZpeFZqMTJxb2tFV1E9PS0tNzJCWU5YU24zUUEvMzhCOVdzdXFNdz09--b395f6e725358b3b79d30a9660cdba5551c8c30a; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: a21d8b9d-09b1-4af9-8cd0-67a60c662d3e
            X-Runtime:
              schema:
                type: number
                example: '7.371579'
            Vary:
              schema:
                type: string
                example: Origin
          content:
            application/json:
              schema:
                type: object
              example:
                plans:
                - _parent_object_id: null
                  id: 5
                  name: Enterprise
                  description: null
                  features: null
                  url: null
                  month_price: null
                - _parent_object_id: null
                  id: 1
                  name: Basic
                  description: Get started on Shyft and try out some features while you decide which plan is right for you.
                  features: null
                  url: null
                  month_price: null
                - _parent_object_id: null
                  id: 2
                  name: Starter
                  description: The perfect plan for small businesses just getting started on Shyft. Priced per location.
                  features: null
                  url: null
                  month_price: null
                - _parent_object_id: null
                  id: 3
                  name: Advanced
                  description: Made for larger teams. Get all the features of Shyft Starter, plus enhanced functionality for Admins. Priced per location.
                  features: null
                  url: null
                  month_price: null
                - _parent_object_id: null
                  id: 4
                  name: Professional
                  description: Everything you need to run your business. Get all the features of Shyft Advanced, and access additional tools with enhanced user management.
                  features: null
                  url: null
                  month_price: null
                meta:
                  pagination:
                    current_page: 1
                    per_page: 500
      operationId: getApiCompactPlans
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
