openapi: 3.2.0
info:
  title: Shyft Customer Customer > GeofenceLogs API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > GeofenceLogs
paths:
  /api/customer/user_role/geofence_logs:
    post:
      tags:
      - Customer > GeofenceLogs
      summary: create geofence_log
      description: 'Input

        - - -


        Attribute | Values

        --- | ---

        action |["approve_user", "reject_user", "delete_user", "rapprove_shift", "reject_shift", "open_shift", "team_availability"]

        passed | true \ false

        reason | ["granted", "location_denied", "location_undetermined", "location_not_recent", "outside_region"]'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n  \"geofence_log\": {\n\t\"location_id\": 2634,\n\t\"latitude\": 45.0,\n\t\"longitude\": 90.0,\n\t\"altitude\": 10,\n\t\"accuracy\": 100,\n\t\"action\": \"approve_shift\",\n\t\"passed\": false,\n\t\"reason\": \"outside_region\"\n  }\n}"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: postApiCustomerUserRoleGeofenceLogs
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
