openapi: 3.0.0
info:
  title: Shyft Customer Authentication > Email Customer > Departments > Memberships API
  description: "Welcome to the Shyft Customer App API.\n\nShyft customer App API is designed to support the function of Shyft Mobile App(iOS, Android), Web App and Manager Dashboard.\n\nNOTES:\n\n- In parameters section, the letter `R` stands for `Required`.\n    \n- All API examples show only essential data set.\n    \n\n## Authentication\n\n---\n\nInclude as headers for API calls after authentication token.\n\n| Name | Values | R | Description |\n| --- | --- | --- | --- |\n| Session-Uukey |  | \\* | The value got from authentication API call (SignIn/Confirm) |\n\n## Global Information\n\n---\n\n#### Query Parameters\n\n###### For All API:\n\n| Name | Values | R | Description |\n| --- | --- | --- | --- |\n| api_version | String |  | Ex. 6_0_0 |\n| response\\[nested\\] | Integer |  | Ex. 1 |\n| response\\[keep\\] | String |  | Ex. location\\[current_user_privilege\\],name,id |\n| response\\[only\\] | String |  | Ex. id,location\\[id,location_name,current_user_privilege\\] |\n| response\\[except\\] | String |  | Ex. name,location\\[id,location_name,swift_code\\],owner\\[id\\] |\n\n- The query parameter `response[only]` is needed to help API performance by limiting the size of returned data.\n    \n- On test server, `response[only]` support wildcard, you can supply `response[only]=\\*` to get everything.\n    \n- Production server does not support wildcard, you need to figure out and supply your `response[only]` for each API call.\n    \n\n###### For Index API:\n\n- Pagination Option 1)\n    \n\n| Name | Values | R | Description |\n| --- | --- | --- | --- |\n| page | Integer |  | Ex. 1 |\n| per_page | Integer |  | Ex. 5 |\n| total | boolean |  | true/false |\n| order | String |  | Ex. start_at_desc, start_at_asc |\n\n- Pagination Option 2)\n    \n\n| Name | Values | R | Description |\n| --- | --- | --- | --- |\n| limit | Integer |  | Ex. 10 |\n| offset | Integer |  | Ex. 5 |\n| order | String |  | Ex. start_at_desc, start_at_asc |\n| last_id | Integer |  | Ex. 101 |\n\n###### For Update API:\n\n| Name | Values | R | Description |\n| --- | --- | --- | --- |\n| response\\[put_return_resource\\] | String |  | Ex. true |\n\n#### Headers\n\n| Name | Values | R | Description |\n| --- | --- | --- | --- |\n| Platform | ios|android|web | \\* |  |\n| Api-Version | 6_0_0 | \\* | Ex: 6_0_0 |\n| Build-Number |  | \\* |  |\n| Push-Id |  |  |  |\n| X-Method |  |  | Deprecated |\n| Content-Type | application/json | \\* |  |\n\n#### Success Codes\n\n| SUCCESS Code | Meaning |\n| --- | --- |\n| 200 | Created -- Objet created. |\n| 201 | Unauthorized -- Your API key is wrong. |\n| 204 | No Content -- Success without returning resource. |\n\n#### Error Codes\n\n| Error Code | Meaning |\n| --- | --- |\n| 400 | Bad Request -- Your request is invalid. |\n| 401 | Unauthorized -- Your API key is wrong. |\n| 403 | Forbidden -- The records requested is hidden for administrators only. |\n| 404 | Not Found -- The specified record could not be found. |\n| 405 | Method Not Allowed -- You tried to access a record with an invalid method. |\n| 406 | Not Acceptable -- You requested a format that isn't json. |\n| 410 | Gone -- The record requested has been removed from our servers. |\n| 422 | Unprocessable Entity -- Invalid input data. |\n| 429 | Too Many Requests -- You're requesting too many requests! Slow down! |\n| 500 | Internal Server Error -- We had a problem with our server. Try again later. |\n| 502 | Bad Gateway -- |\n| 504 | Gateway Timeout -- |\n| 503 | Service Unavailable -- We're temporarily offline for maintenance. Please try again later. |\n\n#### Error Response Formats\n\n422\n\n``` json\n{\n    \"errors\": {\n        \"base\": [\n            \"a private session for same two users already exists: 3034\"\n        ]\n    }\n}\n\n ```\n\n422\n\n```\n{\n    \"errors\": {\n        \"google_map_id\": [\n            \"can't be blank\"\n        ],\n        \"time_zone\": [\n            \"can't be blank\"\n        ],\n        \"longitude\": [\n            \"can't be blank\"\n        ]\n    }\n}\n{\n    \"errors\": {\n        \"record_invalid\": [\n            \"Validation failed: User has already been taken\"\n        ]\n    }\n}\n\n ```\n\n404\n\n``` json\n{\n    \"errors\": {\n        \"not_found\": [\n            \"Couldn't find Post\"\n        ]\n    }\n}\n\n ```\n\n500\n\n``` json\n{\n    \"errors\": {\n        \"internal_server_error\": [\n            \"Invalid nil value\"\n        ]\n    }\n}\n\n ```"
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > Departments > Memberships
paths:
  /api/customer/user_role/department_memberships/mine:
    get:
      tags:
      - Customer > Departments > Memberships
      summary: get mine department memberships
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: location_id
        in: query
        schema:
          type: integer
        example: '2806'
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.19.3
            Date:
              schema:
                type: string
                example: Sun, 18 Sep 2022 05:16:30 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            ETag:
              schema:
                type: string
                example: W/"27b6ff4c59228ad5920b23113d9aa95c"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=SENSWVVhcmFXbnFpUm1FYVlkUDZQMm5pSDhhWHowRXlYWkxJN1VpcWNwaWtBdkZSbVVMNmJXQU1DU3Z6UG1uOTc2bVZhWGFrSWxlWnE1bnVHeE10anc9PS0tdWFLNEw2UE51T3UyVEhlYXQ4TVZUdz09--72fadd74a3019184cfbb4820b8b25e503f24be12; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: dc731dae-a87d-4f2e-9f83-60f9576c0fc7
            X-Runtime:
              schema:
                type: number
                example: '3.560532'
            Vary:
              schema:
                type: string
                example: Origin
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: get mine department memberships
                  value:
                    department_memberships:
                    - _parent_object_id: null
                      id: 10
                      department_id: 1
                      user_privilege_id: 21574
                      user_id: 14815
                      is_main: false
                    meta:
                      pagination:
                        current_page: 1
                        per_page: 25
                example-1:
                  summary: get mine department memberships - with location filter
                  value:
                    department_memberships:
                    - _parent_object_id: null
                      id: 10
                      department_id: 1
                      location_id: 2806
                      user_privilege_id: 21574
                      user_id: 14815
                      is_main: false
                    meta:
                      pagination:
                        current_page: 1
                        per_page: 25
  /api/customer/user_role/department_memberships:
    post:
      tags:
      - Customer > Departments > Memberships
      summary: create a new department membership
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"department_membership\": {\n        \"user_privilege_id\": 21189,\n        \"department_id\": 1, \n        \"is_main\": true\n    }\n}\t"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '201':
          description: Created
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.19.3
            Date:
              schema:
                type: string
                example: Sun, 18 Sep 2022 20:42:22 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            ETag:
              schema:
                type: string
                example: W/"86dddc9d9a9adff6743787ec3ebdbef0"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=YkU2dm5wVExNZmhQUUV5b1pFRWlXamVWM0t2OW5yckwvSy9UazJWZWNmWlJhQVkrRGJLczNyS3dJaGhPOE9ySzZrMGdJR1YxSWNqdTR6azdheVQwc0E9PS0tRlJ4dlhvUmZJMVZCRy82dEp2VFY3Zz09--18d99082d353d1e1c8c8712908b76a8340b5f37a; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: d30ce28d-8f6e-48aa-b24a-8fc248f6333a
            X-Runtime:
              schema:
                type: number
                example: '0.403977'
            Vary:
              schema:
                type: string
                example: Origin
          content:
            application/json:
              schema:
                type: object
              example:
                department_membership:
                  _parent_object_id: null
                  id: 11
                  department_id: 1
                  location_id: 2806
                  user_privilege_id: 21189
                  user_id: 14526
                  is_main: true
  /api/customer/user_role/department_memberships/10:
    put:
      tags:
      - Customer > Departments > Memberships
      summary: udpate a department membership
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"department_membership\": {\n        \"is_main\": true\n    }\n}\t"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '204':
          description: No Content
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.19.3
            Date:
              schema:
                type: string
                example: Sun, 18 Sep 2022 20:58:03 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            Cache-Control:
              schema:
                type: string
                example: no-cache
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=QzBoR3ZRRERjU1BjbE1lRk40MXJXSDlnaDF6dHhBbnExVjdUODl3RzNwb1IwNm9Ua01ieU8yTzVvRzZrMEFjNkxIc3p5c3NzTTJVOXVia2dlZ3ZNTGc9PS0tMjBQNFVYcm9wM0phZ09wSktQRVk3dz09--f82860ed7ce46735676189e5de7a6a57fecaf7fe; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: e070ff33-3337-49e6-a10e-67aecd322e3e
            X-Runtime:
              schema:
                type: number
                example: '0.433338'
            Vary:
              schema:
                type: string
                example: Origin
          content:
            text/plain:
              schema:
                type: string
              example: null
    delete:
      tags:
      - Customer > Departments > Memberships
      summary: delete a department membership
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '204':
          description: No Content
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.19.3
            Date:
              schema:
                type: string
                example: Sun, 18 Sep 2022 21:07:32 GMT
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            Cache-Control:
              schema:
                type: string
                example: no-cache
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=ZUJSUEI4akd6Qnl5MFBNMnJtV0ZiK2hLREtWb3daM2UycWJjTDF6UGJ0NDBIU3Y1VlNLNnVSUWdWMDdjY25TcTZ1b0FmOVJFYm5uUjMycE1iQmIyU1E9PS0tR1V3Z21WRzlMclJrcGxIaFE0aEIydz09--b861167f4bdc17562d3b708e44c70b47193bfdcd; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: 02c8e167-4ae6-4e73-bf33-bd016811d663
            X-Runtime:
              schema:
                type: number
                example: '4.716156'
            Vary:
              schema:
                type: string
                example: Origin
          content:
            text/plain:
              schema:
                type: string
              example: null
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
