openapi: 3.2.0
info:
  title: Shyft Customer Customer > Demands API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > Demands
paths:
  /api/customer/user_role/locations/{location_id}/demands:
    get:
      tags:
      - Customer > Demands
      summary: List Demands
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: location_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiCustomerUserRoleLocationsByLocationIdDemands
      x-operation-id-source: derived
    post:
      tags:
      - Customer > Demands
      summary: Create Demand
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n  \"tag_id\": {{tag_id}},\n  \"is_active\": true,\n  \"demand_schedule\": { \"monday\": [1,2,3] }\n}"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: location_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: postApiCustomerUserRoleLocationsByLocationIdDemands
      x-operation-id-source: derived
  /customer/user_role/locations/{location_id}/demands/{demand_id}:
    get:
      tags:
      - Customer > Demands
      summary: Show Demand
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: location_id
        in: path
        schema:
          type: string
        required: true
      - name: demand_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getCustomerUserRoleLocationsByLocationIdDemandsByDemandId
      x-operation-id-source: derived
  /api/customer/user_role/locations/{location_id}/demands/{demand_id}:
    put:
      tags:
      - Customer > Demands
      summary: Update Demand
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n  \"is_active\": false\n}"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: location_id
        in: path
        schema:
          type: string
        required: true
      - name: demand_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: putApiCustomerUserRoleLocationsByLocationIdDemandsByDemandId
      x-operation-id-source: derived
    delete:
      tags:
      - Customer > Demands
      summary: Delete Demand
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: location_id
        in: path
        schema:
          type: string
        required: true
      - name: demand_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: deleteApiCustomerUserRoleLocationsByLocationIdDemandsByDemandId
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
