openapi: 3.2.0
info:
  title: Shyft Customer Customer > AdminClaims API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > AdminClaims
paths:
  /api/customer/user_role/admin_claims/claim:
    get:
      tags:
      - Customer > AdminClaims
      summary: claim admin by code
      description: 'Input

        - - -


        Attribute | Values | M

        --- | --- | ---'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: activation_code
        in: query
        schema:
          type: string
        description: the code got by email
        example: '{{activation_code}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiCustomerUserRoleAdminClaimsClaim
      x-operation-id-source: derived
  /api/customer/user_role/admin_claims:
    post:
      tags:
      - Customer > AdminClaims
      summary: create admin claim
      description: 'Input

        - - -


        Attribute | Values | M

        --- | --- | ---

        email | your email using for admin claim | Y

        ref_id | target location ID | Y

        email_host | the host of the hyberlink inside the email |


        Output

        - - -


        Attribute | Values |

        --- | ---

        id | recrod ID

        sent_to | sent_to_shyft|sent_to_user'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                admin_claim:
                  email_host: https://manager.myshyft.com
                  email: bin@myshyft.com
                  ref_id: 2634
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: Session-Uukey
        in: header
        schema:
          type: string
        description: '[MESSION] session token UUID. replace `session-token`

          '
        example: '{{session_uukey}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: postApiCustomerUserRoleAdminClaims
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
