openapi: 3.2.0
info:
  title: Shyft Customer Customer > Notifications API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > Notifications
  description: APIs for user/admin to manage notifications belonging to him/her
paths:
  /api/customer/user_role/notifications/145093:
    get:
      tags:
      - Customer > Notifications
      summary: get one notification
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: response[nested]
        in: query
        schema:
          type: integer
        example: '0'
      responses:
        '200':
          description: OK
          headers:
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            ETag:
              schema:
                type: string
                example: W/"324d502f704fc69a095e47c0c3fb5635"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=TlJRU1pNSFU3WUJPV2ZHQ1lUaGVCR0VKcXcxWEpyQ05IZlZ6eVBpSmc1RVNrM3RoUitUek5wWDBOb0tiNTNoWWN0RzI5d0ZxaHptYTB5ZXlPTCsrd1E9PS0tSHdHTnJqV0VrTDFJcE00RGkzYUhHUT09--f42470a924ed8ad736abbf7a3b1ed1326566103e; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: e9851769-af9c-4855-a1cd-b6a3cbae0988
            X-Runtime:
              schema:
                type: number
                example: '0.348971'
            Vary:
              schema:
                type: string
                example: Origin
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
          content:
            application/json:
              schema:
                type: object
              example:
                notification:
                  id: 1159907
                  source: Post
                  source_id: 79848
                  event: like
                  viewed: false
                  message: Ettyk2 Bark2 just posted a shift. ✨ Click here to see the details and be the first to cover it!
                  created_at: '2020-03-25T22:20:39.137Z'
                  object_meta:
                    post_channel_id: 79848
                  sender:
                    id: 14019
                    profile_image:
                      thumb_url: https://shyft-minio.myshyft.com/coffeemobile/images/thumb/11113_14019-20200325_163117_465.jpg?1585179077
                      gallery_url: https://shyft-minio.myshyft.com/coffeemobile/images/gallery/11113_14019-20200325_163117_465.jpg?1585179077
                      full_url: https://shyft-minio.myshyft.com/coffeemobile/images/full/11113_14019-20200325_163117_465.jpg?1585179077
      operationId: getApiCustomerUserRoleNotifications145093
      x-operation-id-source: derived
    put:
      tags:
      - Customer > Notifications
      summary: read one notification
      description: 'Description

        - - -

        - Mark this notification as read already.


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -


        Attribute | Values | R |Description

        --- | --- | --- | ---

        viewed | true | | |'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"notification\": {\n        \"viewed\": true\n    }\n}"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: putApiCustomerUserRoleNotifications145093
      x-operation-id-source: derived
  /api/customer/user_role/notifications/viewed_all:
    put:
      tags:
      - Customer > Notifications
      summary: view all my notifications
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '""'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: putApiCustomerUserRoleNotificationsViewedAll
      x-operation-id-source: derived
  /api/customer/user_role/notifications/destroy_all:
    delete:
      tags:
      - Customer > Notifications
      summary: Remove all my notifications
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: viewed
        in: query
        schema:
          type: boolean
        example: 'true'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: deleteApiCustomerUserRoleNotificationsDestroyAll
      x-operation-id-source: derived
  /api/customer/user_role/notifications/145936:
    delete:
      tags:
      - Customer > Notifications
      summary: Remove one notification
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: deleteApiCustomerUserRoleNotifications145936
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
