openapi: 3.2.0
info:
  title: Shyft Customer Customer > UnregisteredUsers API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > UnregisteredUsers
paths:
  /api/customer/user_role/unregistered_users/466344:
    put:
      tags:
      - Customer > UnregisteredUsers
      summary: '[unregistered users] update unregistered user'
      description: 'Description

        - - -

        - Update a user profile


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -

        Attribute | Values | R |Description

        --- | --- | --- | ---

        locale| en/fr/es | | |'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n\t\"unregistered_user\" : {\n\t\t\"setup_id\": 100\n\t}\n}\n"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: putApiCustomerUserRoleUnregisteredUsers466344
      x-operation-id-source: derived
  /api/customer/user_role/locations/{location_id}/unregistered_users:
    get:
      tags:
      - Customer > UnregisteredUsers
      summary: '[unregistered users] load all uus from a location'
      description: 'Description

        - - -

        - Update a user profile


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -

        Attribute | Values | R |Description

        --- | --- | --- | ---

        locale| en/fr/es | | |'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: location_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiCustomerUserRoleLocationsByLocationIdUnregisteredUsers
      x-operation-id-source: derived
  /api/customer/user_role/locations/{location_id}/unregistered_users/unsettled:
    get:
      tags:
      - Customer > UnregisteredUsers
      summary: '[unregistered users] load all (unsettled) uus from a location'
      description: 'Description

        - - -

        - Update a user profile


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -

        Attribute | Values | R |Description

        --- | --- | --- | ---

        locale| en/fr/es | | |'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: location_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiCustomerUserRoleLocationsByLocationIdUnregisteredUsersUnsettled
      x-operation-id-source: derived
  /api/customer/user_role/unregistered_users/1:
    delete:
      tags:
      - Customer > UnregisteredUsers
      summary: '[unregistered users] delete one'
      description: 'Description

        - - -

        - Update a user profile


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -

        Attribute | Values | R |Description

        --- | --- | --- | ---

        locale| en/fr/es | | |'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: deleteApiCustomerUserRoleUnregisteredUsers1
      x-operation-id-source: derived
  /api/customer/user_role/unregistered_users:
    post:
      tags:
      - Customer > UnregisteredUsers
      summary: '[unregistered users] create one'
      description: 'Description

        - - -

        - Update a user profile


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -

        Attribute | Values | R |Description

        --- | --- | --- | ---

        locale| en/fr/es | | |'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                unregistered_user:
                  location_id: 9286
                  first_name: John
                  last_name: Doe
                  email: john+fake@myshyft.com
                  phone_number: '8880000000'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: postApiCustomerUserRoleUnregisteredUsers
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
