openapi: 3.2.0
info:
  title: Shyft Customer Customer > Applicants API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > Applicants
paths:
  /api/customer/user_role/applicants/{applicant_id}:
    get:
      tags:
      - Customer > Applicants
      summary: '[shifts] get a sginle shift applicant'
      description: 'Description

        - - -

        - Pull one applicant on target posted shift


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---

        applicant_id | integer | * | path variable


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -


        Attribute | Values | R |Description

        --- | --- | --- | ---


        Output

        - - -


        [Applicant Object]


        Attribute | Values | R |Description

        --- | --- | --- | ---

        status | string | | applied / picked / denied'
      security:
      - noauthAuth: []
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: response[keep]
        in: query
        schema:
          type: string
        example: badge_id,internal_id,available
      - name: applicant_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.19.3
            Date:
              schema:
                type: string
                example: Tue, 17 Nov 2020 19:13:27 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            ETag:
              schema:
                type: string
                example: W/"124adfcf3e76271238acd38c0c0988bd"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=OXBMRUljQnMxZ2Z3c1R5WWtzc3hFTnRpZ1J4b0JMaHA1bTVGUzJuY1V2OFZRWnFxWE9CcS84RU9CSzk3SmdyK3hzVURBUElRVjJWQWhhcW1tcWg1L1E9PS0tdGpLTnRFTTYwcEZrVWszNUNWd1hxZz09--bf8a175d8cef2c7a695db174e71bc40e4beb4593; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: 0f75ad8c-b635-402b-8ea4-824730852ab2
            X-Runtime:
              schema:
                type: number
                example: '0.504893'
            Vary:
              schema:
                type: string
                example: Origin
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: '[shifts] [2.0] get a single shift applicant'
                  value:
                    applicant:
                      id: 6
                      status: denied
                      user_id: 11285
                      schedule_element_id: 2564007
                      user:
                        id: 11285
                        first_name: Employee
                        last_name: '1000243'
                        thumb_url: null
                        gallery_url: null
                        full_url: null
                        current_position: null
                example-1:
                  summary: '[shifts] [2.0] get a single shift applicant with  `keep` options'
                  value:
                    applicant:
                      id: 17807
                      status: picked
                      user_id: 14815
                      schedule_element_id: 4319407
                      decider_id: 15527
                      decided_at: '2023-04-05T18:53:57.332Z'
                      final_se_id: 4319408
                      badge_id: null
                      internal_id: null
                      available: true
                      user:
                        id: 14815
                        first_name: Bin
                        last_name: Li
                        thumb_url: https://miniobackingstore.blob.core.windows.net/coffeemobile/images/thumb/21480_14815-20240329_154417_990.jpg?1711752259
                        gallery_url: https://miniobackingstore.blob.core.windows.net/coffeemobile/images/gallery/21480_14815-20240329_154417_990.jpg?1711752259
                        full_url: https://miniobackingstore.blob.core.windows.net/coffeemobile/images/full/21480_14815-20240329_154417_990.jpg?1711752259
                        current_position: null
      operationId: getApiCustomerUserRoleApplicantsByApplicantId
      x-operation-id-source: derived
  /api/customer/user_role/applicants/6:
    delete:
      tags:
      - Customer > Applicants
      summary: '[shifts] cancel you application'
      description: 'Description

        - - -

        - Only application owner can call it.


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---

        applicant_id | integer | * | path variable


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -


        Attribute | Values | R |Description

        --- | --- | --- | ---


        Output

        - - -


        [Applicant Object]


        Attribute | Values | R |Description

        --- | --- | --- | ---

        status | string | | applied / picked / denied'
      security:
      - noauthAuth: []
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '403':
          description: Forbidden
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.19.3
            Date:
              schema:
                type: string
                example: Tue, 17 Nov 2020 19:16:07 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            Cache-Control:
              schema:
                type: string
                example: no-cache
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=SWg2aGVwVVpIejA5YWtHbi9oUEVHem9aQXNzNzVUc1NoQTc2ZFo0N3M4WEVjVFlqUm41S05qZ2YzU2srQ2dlVG41NnRxT1RBN3NUWDhFMWVySXUyaFE9PS0tQndzKzhpKzVNeUQxTFptNWxMN2hrUT09--4b9c85fbd7b45369f7840267c7fd2858edfa420b; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: 47de3b0f-e4bf-42bc-b484-5b8c0ff9905f
            X-Runtime:
              schema:
                type: number
                example: '2.177342'
            Vary:
              schema:
                type: string
                example: Origin
          content:
            application/json:
              schema:
                type: object
              example:
                errors:
                  forbidden:
                  - Not authorized to perform requested action.
      operationId: deleteApiCustomerUserRoleApplicants6
      x-operation-id-source: derived
  /api/customer/user_role/locations/5459/applicants:
    get:
      tags:
      - Customer > Applicants
      summary: get a location's applicants
      description: 'NOTE: Only applicable for `shift post` , otherwise raise `403`'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: ids
        in: query
        schema:
          type: string
        example: 1120,1030
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiCustomerUserRoleLocations5459Applicants
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
