openapi: 3.2.0
info:
  title: Shyft Customer Customer > UserPrivileges > admin_role API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > UserPrivileges > admin_role
paths:
  /api/customer/admin_role/user_privileges:
    get:
      tags:
      - Customer > UserPrivileges > admin_role
      summary: '[user_privilege] get managable user privielges'
      security:
      - bearerAuth: []
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: c14cbc26-a5d9-45c3-8ab9-cb4de0ac8ba3
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: search_term
        in: query
        schema:
          type: string
        example: ABCD
      - name: location_id
        in: query
        schema:
          type: integer
        example: '5493'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiCustomerAdminRoleUserPrivileges
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
