openapi: 3.2.0
info:
  title: Shyft Customer Customer > Segments API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer Segments
paths:
  /api/customer/user_role/schedule_elements/7715:
    get:
      tags:
      - Customer Segments
      summary: '[shifts] get segments'
      security:
      - noauthAuth: []
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiCustomerUserRoleScheduleElements7715
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
