openapi: 3.2.0
info:
  title: Shyft Customer Customer > AI API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > AI
paths:
  /api/customer/ai_agent/command:
    post:
      tags:
      - Customer > AI
      summary: AI Ccommands
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                message: Schedule John Doe every Monday and Wednesday for 3 weeks from 08:00 to 16:00 at Site A.
                users:
                - John Doe
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.27.5
            Date:
              schema:
                type: string
                example: Wed, 11 Jun 2025 22:47:04 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            ETag:
              schema:
                type: string
                example: W/"24421b5fdc6cff2a054d941e25e82775"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=WS9yVXVsOGZBZ1AwOVBFN0J5WDFTNWlTdXdjK0Z3Q2pWdVZSWUJuSERJUEYwak9OTEZCamI5c3lJTnEybGRNQ1g5bmRZWThaVEJodlFxbnJYbkxjNGc9PS0tNHJWKzY1cHlaSEpFYU9HaGxBdlAzQT09--c3977b74d64766339675f0573460b6e19fa0922a; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: 39ab5c3d-8033-4545-a804-468a83c21486
            X-Runtime:
              schema:
                type: number
                example: '20.543644'
            Vary:
              schema:
                type: string
                example: Origin
          content:
            application/json:
              schema:
                type: object
              example:
                reply: '📋 john doe: 2025-06-16 08:00 - 16:00 @ Site A

                  📋 john doe: 2025-06-23 08:00 - 16:00 @ Site A

                  📋 john doe: 2025-06-30 08:00 - 16:00 @ Site A

                  📋 john doe: 2025-06-11 08:00 - 16:00 @ Site A

                  📋 john doe: 2025-06-18 08:00 - 16:00 @ Site A

                  📋 john doe: 2025-06-25 08:00 - 16:00 @ Site A


                  ✅ Type "confirm" to create these shifts or "cancel" to discard.'
      operationId: postApiCustomerAiAgentCommand
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
