openapi: 3.2.0
info:
  title: Shyft Customer Compact > Subscriptions API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Compact > Subscriptions
paths:
  /api/compact/subscriptions/can_view:
    get:
      tags:
      - Compact > Subscriptions
      summary: get viewable subscriptions
      description: Get all my subscriptions
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: channel_id
        in: query
        schema:
          type: integer
        description: 'filter my subscriptions by channel

          '
        example: '7336'
      responses:
        '200':
          description: OK
          headers:
            Server:
              schema:
                type: string
                example: nginx/1.19.3
            Date:
              schema:
                type: string
                example: Tue, 20 Apr 2021 20:54:17 GMT
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Connection:
              schema:
                type: string
                example: keep-alive
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            ETag:
              schema:
                type: string
                example: W/"ff8c5f87fd05966138fee4a2a1356390"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=Tm9VSXZuZ3lnTngxNWcyR3IycGdLTWZnV0dnZmMvajFHRlk5NVVDMHBYZVFSbzBlb29ENG52UzR3SWtqdFRNL2ZBeGtNSFQwdXk3d0o2S0QxblVzdFE9PS0tRzFTZWdDcmtFSjBNQjM1S0RyTGcxQT09--c64cf2daf1e990a8ff274527abd5c6eda2de0839; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: BinLocalServer
            X-Request-Id:
              schema:
                type: string
                example: b4edbfe3-2b98-42ef-9762-4d2e047cc10f
            X-Runtime:
              schema:
                type: number
                example: '0.225400'
            Vary:
              schema:
                type: string
                example: Origin
          content:
            application/json:
              schema:
                type: object
              example:
                subscriptions:
                - _parent_object_id: null
                  id: 19294
                  user_id: 9579
                  channel_id: 7336
                - _parent_object_id: null
                  id: 19295
                  user_id: 9574
                  channel_id: 7336
                - _parent_object_id: null
                  id: 19296
                  user_id: 9578
                  channel_id: 7336
                - _parent_object_id: null
                  id: 19297
                  user_id: 9582
                  channel_id: 7336
                - _parent_object_id: null
                  id: 19298
                  user_id: 9576
                  channel_id: 7336
                - _parent_object_id: null
                  id: 19293
                  user_id: 9577
                  channel_id: 7336
                - _parent_object_id: null
                  id: 23783
                  user_id: 11284
                  channel_id: 7336
                meta:
                  pagination:
                    current_page: 1
                    per_page: 500
      operationId: getApiCompactSubscriptionsCanView
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
