openapi: 3.2.0
info:
  title: Shyft Customer Customer > ToS API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > ToS
paths:
  /api/customer/user_role/legal_user_privileges:
    post:
      tags:
      - Customer > ToS
      summary: approve/deny TOS
      description: 'Description

        - - -

        - Approve/Deny ToS


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -


        Attribute | Values | R |Description

        --- | --- | --- | ---

        user_privilege_id | | * |

        legal_id | | * | you get it inside user''s user privilege object

        status | | * | accepted/denied'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n  \"legal_user_privilege\": {\n  \t\"user_privilege_id\": 2,\n    \"legal_id\": 1,\n    \"status\": \"denied\"\n  }\n}\t"'
      parameters:
      - name: Platform
        in: header
        schema:
          type: string
        example: '{{platform}}'
      - name: Version
        in: header
        schema:
          type: string
        example: '{{version}}'
      - name: Build-Number
        in: header
        schema:
          type: string
        example: '{{build_number}}'
      - name: Push-Id
        in: header
        schema:
          type: string
        example: '{{push_id}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: Session-Token
        in: header
        schema:
          type: integer
        example: '30216'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: postApiCustomerUserRoleLegalUserPrivileges
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
