openapi: 3.2.0
info:
  title: Shyft Customer Customer > Tag API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > Tag
paths:
  /api/customer/user_role/locations/2806/assign_skill_users/1:
    put:
      tags:
      - Customer > Tag
      summary: assign a location tag's users
      description: 'Description

        - - -

        - Update a location

        - `location_id` coulld be `ID` or `Swift Code`


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -

        Attribute | Values | R |Description

        --- | --- | --- | ---

        shift_require_approval| true/false| | |

        require_approval| true/false| | |

        allow_tipping| true/false| | |

        admin_delete_content| true/false| | |'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    // \"user_ids\": [0, 1],\n    \"remove_user_ids\": [9456],\n    \"add_user_ids\": [9456]\n}"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: response[put_return_resource]
        in: query
        schema:
          type: boolean
        example: 'true'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: putApiCustomerUserRoleLocations2806AssignSkillUsers1
      x-operation-id-source: derived
  /api/customer/user_role/locations/2806/tags/managable:
    get:
      tags:
      - Customer > Tag
      summary: list location's managable tags
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiCustomerUserRoleLocations2806TagsManagable
      x-operation-id-source: derived
  /api/customer/user_role/locations/2806/tags:
    get:
      tags:
      - Customer > Tag
      summary: list location's tags
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiCustomerUserRoleLocations2806Tags
      x-operation-id-source: derived
    post:
      tags:
      - Customer > Tag
      summary: create a new tag
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                tag:
                  name: Sample tag
                  tag_type: role
                  color_code: '#FF5733'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: postApiCustomerUserRoleLocations2806Tags
      x-operation-id-source: derived
  /api/customer/user_role/locations/2806/tags/{tag_id}:
    get:
      tags:
      - Customer > Tag
      summary: read a tag
      parameters:
      - name: tag_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiCustomerUserRoleLocations2806TagsByTagId
      x-operation-id-source: derived
    put:
      tags:
      - Customer > Tag
      summary: update a tag
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"tag\": {\n        \"name\": \"New tag\"\n    }\n}"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: tag_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: putApiCustomerUserRoleLocations2806TagsByTagId
      x-operation-id-source: derived
    delete:
      tags:
      - Customer > Tag
      summary: delete a tag
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: tag_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: deleteApiCustomerUserRoleLocations2806TagsByTagId
      x-operation-id-source: derived
  /api/customer/user_role/locations/2806/assign_tags:
    put:
      tags:
      - Customer > Tag
      summary: assign a location tags
      description: 'Description

        - - -

        - Update a location

        - `location_id` coulld be `ID` or `Swift Code`


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -

        Attribute | Values | R |Description

        --- | --- | --- | ---

        shift_require_approval| true/false| | |

        require_approval| true/false| | |

        allow_tipping| true/false| | |

        admin_delete_content| true/false| | |'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"linked_tag_ids\": [1, 2]\n    // \"add_tag_ids\": [3],\n    // \"removej_tag_ids\": [4]\n}"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: response[put_return_resource]
        in: query
        schema:
          type: boolean
        example: 'true'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: putApiCustomerUserRoleLocations2806AssignTags
      x-operation-id-source: derived
  /api/customer/user_role/locations/2806/assign_user_tags/7613:
    put:
      tags:
      - Customer > Tag
      summary: assign a location user's tags
      description: 'Description

        - - -

        - Update a location

        - `location_id` coulld be `ID` or `Swift Code`


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -

        Attribute | Values | R |Description

        --- | --- | --- | ---

        shift_require_approval| true/false| | |

        require_approval| true/false| | |

        allow_tipping| true/false| | |

        admin_delete_content| true/false| | |'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"tag_ids\": [1, 2]\n    // \"add_tag_ids\": [3],\n    // \"removej_tag_ids\": [4]\n}"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: response[put_return_resource]
        in: query
        schema:
          type: boolean
        example: 'true'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: putApiCustomerUserRoleLocations2806AssignUserTags7613
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
