openapi: 3.2.0
info:
  title: Shyft Customer Customer > Products API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer Products
paths:
  /api/customer/user_role/users/{user_id}/fetch_products:
    post:
      tags:
      - Customer Products
      summary: fetch products
      description: 'Description

        - - -

        - A API for get productions list

        - It follows the v5 schema


        Params

        - - -

        Param | Values | R |Description

        --- | --- | --- | ---

        platform | string |*| ios/android


        Headers

        - - -

        Header | Values | R |Description

        --- | --- | --- | ---


        Input

        - - -


        Attribute | Values | R |Description

        --- | --- | --- | ---'
      requestBody:
        content: {}
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: platform
        in: query
        schema:
          type: string
        example: android
      - name: user_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: OK
          headers:
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: none
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            ETag:
              schema:
                type: string
                example: W/"809edefb2b225ee185938bbf5b6f0ce2"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=SDdUVnVpTzFvT0JzVm1sWkhKOUVxa3hTdHZUVWR4TUYwV2F2YW9iRS9OdmdvbnBJVGtWOWJrT0c0NHZuc0VDWlN3UXdMeWtGck5iNDlQN2FqS21NV0E9PS0tZExJd2N4MkVRTk40aTcvb3V5d20yZz09--f5a256d09a4f2f3e8499daba91b0acac81859ad4; path=/; secure; HttpOnly
            X-Request-Id:
              schema:
                type: string
                example: 9802ca9d-072b-4e74-b96d-9b0072cf6823
            X-Runtime:
              schema:
                type: number
                example: '0.090588'
            Vary:
              schema:
                type: string
                example: Origin
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Content-Encoding:
              schema:
                type: string
                example: gzip
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=31536000;
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: fetch products - iOS
                  value:
                    eXpresso:
                      products:
                      - - pro_1_5
                        - $59.99/mo
                        - ''
                      - - pro_6_5
                        - $329.99
                        - SAVE 8%
                      - - pro_12_5
                        - $599.99
                        - SAVE 17%
                example-1:
                  summary: fetch products - android
                  value:
                    eXpresso:
                      products:
                      - - shyft_pro_1_diamond
                        - $59.99/mo
                        - ''
                      - - shyft_pro_3_diamond
                        - $56.99/mo
                        - SAVE 5%
                      - - shyft_pro_6_diamond
                        - $54.99/mo
                        - SAVE 8%
      operationId: postApiCustomerUserRoleUsersByUserIdFetchProducts
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
