openapi: 3.2.0
info:
  title: Shyft Customer Customer > SsoSessions API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > SsoSessions
paths:
  /api/customer/user_role/sso_sessions/renew:
    post:
      tags:
      - Customer > SsoSessions
      summary: '[users] renew sso session'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '""'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: sso_provider_name
        in: query
        schema:
          type: string
        example: sso_gap
      - name: code
        in: query
        schema:
          type: string
        example: QDVMClwBkPvlOZ-In4MtQzPWHrRQAmEZwjofhgAe
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: postApiCustomerUserRoleSsoSessionsRenew
      x-operation-id-source: derived
  /api/customer/user_role/sso_sessions/{sso_session_id}/link:
    put:
      tags:
      - Customer > SsoSessions
      summary: '[users] link sso_session to current_user'
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '""'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: sso_session_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: putApiCustomerUserRoleSsoSessionsBySsoSessionIdLink
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
