openapi: 3.2.0
info:
  title: Shyft Customer Customer > Comments API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > Comments
paths:
  /api/customer/user_role/comments:
    get:
      tags:
      - Customer > Comments
      summary: get comments
      description: please supply `post_id` for getting commeents for particular post
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: response[nested]
        in: query
        schema:
          type: integer
        example: '2'
      - name: response[keep]
        in: query
        schema:
          type: string
        example: like_owners
      - name: post_id
        in: query
        schema:
          type: integer
        example: '143548'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiCustomerUserRoleComments
      x-operation-id-source: derived
    post:
      tags:
      - Customer > Comments
      summary: create comment
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '" {\n    \"comment\": {  \n\t    \"source_id\": \"22120\",\n\t    \"content\": \"Here is my comment!\"\n\t}\n}"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '201':
          description: Created
          headers:
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-LS-License:
              schema:
                type: string
                example: All Rights Reserved Â© Coffee Enterprise
            X-LS-Application:
              schema:
                type: string
                example: Coffee Mobile
            X-Request-Method:
              schema:
                type: string
                example: '{{x_method}}'
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            ETag:
              schema:
                type: string
                example: W/"1925589f0f845d77954b1c01320a724c"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            Set-Cookie:
              schema:
                type: string
                example: _shyft_api_server_session=QVFUV1d5RW5TMHQycWh3eGdUL1pjQnRrSElUTHZtU0IwcmxrNGVpNEw2ODV0RUpDcVU2QnJrY3JEd2NvVlA1bFB1ZjJYSTM1OGFudkFMTE9BcnEvNkNSR3ZDMEc3TGUrZnJKbTlOdjRXOVhKS0M4aWUxb2lNVE1Zdmg3ODRDUytJNmczaXVUV3pHWHhkQ0h4ZGFxeVhBQ0htZ1BjejZjZzUwcTZVdURxdldPdGtUVHR4YlNYTjBzb3luVHNkQUdZdWVvRXhINmtyQWZ1MkFnNmRmSkFhbDlXTitiZjZ5MFRqVGFVQTY1aGNOcz0tLUlQZ0pkUXBJV29QQkxIN2RPMHdKb0E9PQ%3D%3D--236d143e2721d800baa7c371b62c123ce7feaed6; path=/; HttpOnly
            X-Rack-Dev-Mark-Env:
              schema:
                type: string
                example: Bin%27s+Local+Server
            X-Request-Id:
              schema:
                type: string
                example: d3b144b1-f5c4-4572-ad10-ef8af0f4b74a
            X-Runtime:
              schema:
                type: number
                example: '26.358253'
            Vary:
              schema:
                type: string
                example: Origin
            Connection:
              schema:
                type: string
                example: close
            Server:
              schema:
                type: string
                example: thin 1.5.1 codename Straight Razor
          content:
            application/json:
              schema:
                type: object
              example:
                comment:
                  _parent_object_id: null
                  id: 6247
                  content: Here is my comment!
                  source_id: 22120
                  likes_count: 0
                  created_at: '2018-10-16T04:15:42.800Z'
                  liked: false
                  flagged: false
                  allow_delete: true
                  owner:
                    _parent_object_id: 6247
                    id: 9064
                    active_org: 0
                    first_name: Bin
                    last_name: Li
                    email: bin+104@myshyft.com
                    gender: 0
                    chat_handle: ab4693b99883e10dd5e7d17d0cf71200
                    user_group: 0
                    status: ''
                    profile_image:
                      thumb_url: https://coffeemobile.s3.amazonaws.com/images/thumb/8352_data.?1512600950
                      gallery_url: https://coffeemobile.s3.amazonaws.com/images/gallery/8352_data.?1512600950
                      full_url: https://coffeemobile.s3.amazonaws.com/images/full/8352_data.?1512600950
                    recent_user_privilege:
                      _parent_object_id: 9064
                      id: 11336
                      email: bin+104@myshyft.com
                      wage: 15
                      position: null
                      is_approved: true
                      owner_id: 9064
                      location_id: 2324
                      org_id: 1
                      is_admin: true
                      read_only: false
                      first_name: Bin
                      last_name: Li
                      phone_number: '18880006511'
                      profile_image_thumb_url: https://coffeemobile.s3.amazonaws.com/images/thumb/8352_data.?1512600950
                      admin_claim_pending: false
                      current_availability: null
                      location:
                        _associations_removed: true
                        _parent_object_id: 11336
                        id: 2324
                        swift_code: QO9021
                        location_name: Comfort Inn & Suites Bothell - Seattle North
                        unit_number: null
                        street_number: null
                        address: 1414 228th Street Southeast
                        province: Washington
                        postal: '98021'
                        country: United States
                        lat: '47.790475'
                        lng: '-122.213519'
                        latitude: 47.7904654
                        longitude: -122.2135587
                        phone_number: +1 425-402-0900
                        created_at: '2017-10-16T07:10:35.423Z'
                        users_count: 3
                        formatted_address: 1414 228th St SE, Bothell, WA 98021, USA
                        time_zone: null
                        google_map_id: ChIJA0sL1qkPkFQR43qJWFmWqvo
                        allow_tipping: true
                        shift_require_approval: false
                        shyft_pro_active: false
                        shyft_pro_expiry_date: '2018-12-04T19:10:49.425Z'
                        fence_radius: null
                        cfg_not_dm: false
                        cfg_geofence_log: null
                        cfg_timeout: null
                        tos_url: null
                        tos_version: null
                        ip_blocked: false
                        member_count: 3
                        location_address: null
                        location_city: Bothell, Washington, 98021
                        division_names: []
                        feed_channel_id: 4359
                      user:
                        _associations_removed: true
                        _parent_object_id: 11336
                        id: 9064
                        active_org: 0
                        first_name: Bin
                        last_name: Li
                        email: bin+104@myshyft.com
                        gender: 0
                        chat_handle: ab4693b99883e10dd5e7d17d0cf71200
                        user_group: 0
                        status: ''
      operationId: postApiCustomerUserRoleComments
      x-operation-id-source: derived
  /api/customer/user_role/comments/7093:
    get:
      tags:
      - Customer > Comments
      summary: get a single comment
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiCustomerUserRoleComments7093
      x-operation-id-source: derived
  /api/customer/user_role/comments/6649:
    delete:
      tags:
      - Customer > Comments
      summary: delete comment
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: deleteApiCustomerUserRoleComments6649
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
