openapi: 3.2.0
info:
  title: Shyft Customer Customer > Availabilities > user_role >…
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > Availabilities > user_role > Deprecated
paths:
  /api/customer/user_role/locations/{location_id}/availabilities/all_current:
    get:
      tags:
      - Customer > Availabilities > user_role > Deprecated
      summary: '[availabilities] get members'' current availabilites'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: location_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: 'OK '
          headers:
            Platform:
              schema:
                type: string
                example: '{{platform}}'
            Version:
              schema:
                type: string
                example: '{{version}}'
            Build-Number:
              schema:
                type: string
                example: '{{build_number}}'
            Push-Id:
              schema:
                type: string
                example: '{{push_id}}'
            X-Method:
              schema:
                type: string
                example: '{{x_method}}'
            Session-Token:
              schema:
                type: string
                example: '{{session_token}}'
            Session-Uukey:
              schema:
                type: string
                example: '{{session_uukey}}'
            Authorization:
              schema:
                type: string
                example: Token token={{api_key_access_token}}
            Uid:
              schema:
                type: string
                example: '{{uid}}'
            Auth-Category:
              schema:
                type: string
                example: '{{auth_category}}'
            Auth-Target:
              schema:
                type: string
                example: '{{auth_target}}'
            Token-Type:
              schema:
                type: string
                example: Bearer
            Client:
              schema:
                type: string
                example: '{{client}}'
            Access-Token:
              schema:
                type: string
                example: '{{access_token}}'
            Expiry:
              schema:
                type: string
                example: '{{expiry}}'
          content:
            application/json:
              schema:
                type: object
              examples:
                example-0:
                  summary: '[availabilities] get members'' current availabilites for particular user'
                  value:
                    availabilities:
                    - id: 77
                      status: pending
                      notes: null
                      user_id: 9046
                      location_id: 2159
                      availability_request_id: 12
                      sunday:
                        start_at: 00:00
                        end_at: null
                      monday:
                        start_at: '10:00'
                        end_at: '12:00'
                      tuesday:
                        start_at: null
                        end_at: '12:00'
                      wednesday:
                        start_at: null
                        end_at: null
                      thursday:
                        start_at: null
                        end_at: null
                      friday:
                        start_at: null
                        end_at: null
                      saturday:
                        start_at: null
                        end_at: null
                      user:
                        id: 9046
                        active_org: 1
                        first_name: BIN
                        last_name: null
                        email: libin0120@gmail.com
                        gender: 0
                        chat_handle: 3704ed17fd20978c115c87aa554d2565
                        user_group: Team member
                        position: Team member
                        location: Location
                        status: ''
                        profile_image: null
                example-1:
                  summary: '[availabilities] get members'' current availabilites'
                  value:
                    availabilities:
                    - id: 77
                      status: pending
                      notes: null
                      user_id: 9046
                      location_id: 2159
                      availability_request_id: 12
                      sunday:
                        start_at: 00:00
                        end_at: null
                      monday:
                        start_at: '10:00'
                        end_at: '12:00'
                      tuesday:
                        start_at: null
                        end_at: '12:00'
                      wednesday:
                        start_at: null
                        end_at: null
                      thursday:
                        start_at: null
                        end_at: null
                      friday:
                        start_at: null
                        end_at: null
                      saturday:
                        start_at: null
                        end_at: null
                      user:
                        id: 9046
                        active_org: 1
                        first_name: BIN
                        last_name: null
                        email: libin0120@gmail.com
                        gender: 0
                        chat_handle: 3704ed17fd20978c115c87aa554d2565
                        user_group: Team member
                        position: Team member
                        location: Location
                        status: ''
                        profile_image: null
      operationId: getApiCustomerUserRoleLocationsByLocationIdAvailabilitiesAllCurrent
      x-operation-id-source: derived
  /api/customer/user_role/locations/{location_id}/availabilities/mine_current:
    get:
      tags:
      - Customer > Availabilities > user_role > Deprecated
      summary: '[availabilities] get your current availability'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: location_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: 'OK '
          headers:
            Platform:
              schema:
                type: string
                example: '{{platform}}'
            Version:
              schema:
                type: string
                example: '{{version}}'
            Build-Number:
              schema:
                type: string
                example: '{{build_number}}'
            Push-Id:
              schema:
                type: string
                example: '{{push_id}}'
            X-Method:
              schema:
                type: string
                example: '{{x_method}}'
            Session-Token:
              schema:
                type: string
                example: '{{session_token}}'
            Session-Uukey:
              schema:
                type: string
                example: '{{session_uukey}}'
            Authorization:
              schema:
                type: string
                example: Token token={{api_key_access_token}}
            Uid:
              schema:
                type: string
                example: '{{uid}}'
            Auth-Category:
              schema:
                type: string
                example: '{{auth_category}}'
            Auth-Target:
              schema:
                type: string
                example: '{{auth_target}}'
            Token-Type:
              schema:
                type: string
                example: Bearer
            Client:
              schema:
                type: string
                example: '{{client}}'
            Access-Token:
              schema:
                type: string
                example: '{{access_token}}'
            Expiry:
              schema:
                type: string
                example: '{{expiry}}'
          content:
            application/json:
              schema:
                type: object
              example:
                availability:
                  id: 77
                  status: pending
                  notes: null
                  user_id: 9046
                  location_id: 2159
                  availability_request_id: 12
                  sunday:
                    start_at: 00:00
                    end_at: null
                  monday:
                    start_at: '10:00'
                    end_at: '12:00'
                  tuesday:
                    start_at: null
                    end_at: '12:00'
                  wednesday:
                    start_at: null
                    end_at: null
                  thursday:
                    start_at: null
                    end_at: null
                  friday:
                    start_at: null
                    end_at: null
                  saturday:
                    start_at: null
                    end_at: null
      operationId: getApiCustomerUserRoleLocationsByLocationIdAvailabilitiesMineCurrent
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
