openapi: 3.2.0
info:
  title: Shyft Customer Authentication > Email API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Authentication > Email
paths:
  /api/users/confirmation:
    get:
      tags:
      - Authentication > Email
      summary: Email - Confirmation
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: confirmation_token
        in: query
        schema:
          type: string
        example: Q9-ZCwF5krHdxcih6xuR
      responses:
        '422':
          description: Unprocessable Entity
          headers:
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Cache-Control:
              schema:
                type: string
                example: no-cache
            X-Request-Id:
              schema:
                type: string
                example: ea70a1b2-eb3b-403d-9ee9-2218222edbd2
            X-Runtime:
              schema:
                type: number
                example: '0.245714'
            Vary:
              schema:
                type: string
                example: Origin
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=31536000;
          content:
            application/json:
              schema:
                type: object
              example:
                confirmation_token:
                - is invalid
      operationId: getApiUsersConfirmation
      x-operation-id-source: derived
    post:
      tags:
      - Authentication > Email
      summary: Email - Confirmation Resend
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n    \"api_user\": {\n        \"email\": \"bin@myshyft.com\"\n    }\n}"'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '201':
          description: Created
          headers:
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            Location:
              schema:
                type: string
                example: /
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            ETag:
              schema:
                type: string
                example: W/"44136fa355b3678a1146ad16f7e8649e"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            X-Request-Id:
              schema:
                type: string
                example: 01185e12-32d5-445f-9d96-b77a974cd789
            X-Runtime:
              schema:
                type: number
                example: '0.706196'
            Vary:
              schema:
                type: string
                example: Origin
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Content-Encoding:
              schema:
                type: string
                example: gzip
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=31536000;
          content:
            application/json:
              schema:
                type: object
              example: {}
      operationId: postApiUsersConfirmation
      x-operation-id-source: derived
  /api/users/password:
    post:
      tags:
      - Authentication > Email
      summary: Email - Reset Password (request)
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n  \"api_user\": { \n    \"email\": \"bin@myshyft.com\", \n    \"email_host\": \"127.0.0.1\"\n  }\n}"'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '201':
          description: Created
          headers:
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            ETag:
              schema:
                type: string
                example: W/"44136fa355b3678a1146ad16f7e8649e"
            Cache-Control:
              schema:
                type: string
                example: max-age=0, private, must-revalidate
            X-Request-Id:
              schema:
                type: string
                example: 99608652-72e1-4c0e-93cf-64c6a6444d69
            X-Runtime:
              schema:
                type: number
                example: '0.731369'
            Vary:
              schema:
                type: string
                example: Origin
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Content-Encoding:
              schema:
                type: string
                example: gzip
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=31536000;
          content:
            application/json:
              schema:
                type: object
              example: {}
      operationId: postApiUsersPassword
      x-operation-id-source: derived
    put:
      tags:
      - Authentication > Email
      summary: Email - Reset Password (update)
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n\t\"api_user\": {\n\t\t\"reset_password_token\": \"VKshw-iZym8Be4Wz6fDD\",\n\t\t\"password\": \"11111111\",\n\t\t\"password_confirmation\": \"11111111\"\n\t}\n}"'
      parameters:
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '422':
          description: Unprocessable Entity
          headers:
            X-Frame-Options:
              schema:
                type: string
                example: SAMEORIGIN
            X-XSS-Protection:
              schema:
                type: string
                example: 1; mode=block
            X-Content-Type-Options:
              schema:
                type: string
                example: nosniff
            X-Download-Options:
              schema:
                type: string
                example: noopen
            X-Permitted-Cross-Domain-Policies:
              schema:
                type: string
                example: none
            Referrer-Policy:
              schema:
                type: string
                example: strict-origin-when-cross-origin
            Content-Type:
              schema:
                type: string
                example: application/json; charset=utf-8
            Cache-Control:
              schema:
                type: string
                example: no-cache
            X-Request-Id:
              schema:
                type: string
                example: 02dc5afd-8f87-4961-aafd-cf9588fd4fa9
            X-Runtime:
              schema:
                type: number
                example: '0.249326'
            Vary:
              schema:
                type: string
                example: Origin
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            Strict-Transport-Security:
              schema:
                type: string
                example: max-age=31536000;
          content:
            application/json:
              schema:
                type: object
              example:
                errors:
                  reset_password_token:
                  - is invalid
      operationId: putApiUsersPassword
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
