openapi: 3.2.0
info:
  title: Shyft Customer Customer > Messions API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > Messions
paths:
  /api/customer/user_role/messions/{mession_id}/test_push:
    get:
      tags:
      - Customer > Messions
      summary: Get test push notification
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: mession_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiCustomerUserRoleMessionsByMessionIdTestPush
      x-operation-id-source: derived
  /api/customer/user_role/messions/{mession_id}:
    put:
      tags:
      - Customer > Messions
      summary: Update mession
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n\t\"mession\" : {\n\t\t\"push_id\": \"0319b0b3f56c95904a051913dcd348985236053ed94e1d1da5bb7aadfe379620\"\n\t}\n}\n"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: mession_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: putApiCustomerUserRoleMessionsByMessionId
      x-operation-id-source: derived
  /api/customer/user_role/messions/{session_uukey}:
    delete:
      tags:
      - Customer > Messions
      summary: Logout mession - Deprecated
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: session_uukey
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: deleteApiCustomerUserRoleMessionsBySessionUukey
      x-operation-id-source: derived
  /api/customer/user_role/messions/logout:
    delete:
      tags:
      - Customer > Messions
      summary: Logout mession - Option 2
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: deleteApiCustomerUserRoleMessionsLogout
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
