openapi: 3.2.0
info:
  title: Shyft Customer Customer > UserNews API
  description: Welcome to the Shyft Customer App API.
  version: 1.0.0
servers:
- url: http://{{host}}
- url: http://{{local-host}}
- url: http://{{sp3-host}}
- url: http://test-service.myshyft.com
- url: http://localhost:4001
- url: http://localhost:3000
- url: http://{{local-host}}api
- url: https://test-unfurl.myshyft.com
tags:
- name: Customer > UserNews
paths:
  /api/customer/user_role/user_news:
    get:
      tags:
      - Customer > UserNews
      summary: get user news
      description: Get only not viewed, not expired and already sent news.
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: location_id
        in: query
        schema:
          type: integer
        example: '5487'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiCustomerUserRoleUserNews
      x-operation-id-source: derived
  /api/customer/user_role/user_news/613:
    get:
      tags:
      - Customer > UserNews
      summary: show usernews
      description: Get only not viewed, not expired and already sent news.
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: getApiCustomerUserRoleUserNews613
      x-operation-id-source: derived
  /api/customer/user_role/user_news/{user_news_id}:
    put:
      tags:
      - Customer > UserNews
      summary: update user new as viewed
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              example: '"{\n  \"user_news\": {\n    \"is_viewed\": true\n  }\n}"'
      parameters:
      - name: Session-Uukey
        in: header
        schema:
          type: string
        example: '{{session_uukey}}'
      - name: Content-Type
        in: header
        schema:
          type: string
        example: application/json
      - name: user_news_id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
      operationId: putApiCustomerUserRoleUserNewsByUserNewsId
      x-operation-id-source: derived
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
